### ISSUE TITLE
Incorrect download progress

### ISSUE THREAD

**Issue by jesussmile** [rodolfogoulart/cloudflare_r2#4]
sorry to be the first one with an issue ,
However I get this , the download percentage is in 1000's
```dart
  await CloudFlareR2.getObject(
        bucket: 'flightcanvas',
        objectName: 'tiles/us_tiles/$tiles',
        pathToSave: filePath,
        onReceiveProgress: (total, received) {
          if (total > 0) {
            // Fix progress calculation
            final progress = received.toDouble() / total.toDouble();
            print('Download progress: ${(progress).toStringAsFixed(2)}%');
            //  print('Download progress: ${(progress * 100).toStringAsFixed(2)}%');
            _setDownloadProgress(
                progress); // Use _setDownloadProgress instead of _setProgress
            prefs.setInt('bytesTransferred_$tiles', received);
            notifyListeners(); // Ensure UI updates
          }
        },
      );

```
```
I/flutter ( 4027): Download progress: 896790.63%
I/flutter ( 4027): Download progress: 448395.31%
I/flutter ( 4027): Download progress: 298930.21%
I/flutter ( 4027): Download progress: 224197.66%
I/flutter ( 4027): Download progress: 179358.13%
I/flutter ( 4027): Download progress: 149465.10%
I/flutter ( 4027): Download progress: 128112.95%
I/flutter ( 4027): Download progress: 112098.83%
I/flutter ( 4027): Download progress: 99643.40%
I/flutter ( 4027): Download progress: 89679.06%
I/flutter ( 4027): Download progress: 81526.42%
```

**Comment by rodolfogoulart** [comment]
Hi @jesussmile, sorry for putting a incorrect example on the package i will fix this.

But with the example that you gave, if you want the percent from the download correct you need to fix your code on the  `onReceiveProgress: (total, received) {`, you changed the params, it shoud be `onReceiveProgress: (received, total) {` and fix the calc by doing `received / total * 100`


your code

```dart
  await CloudFlareR2.getObject(
        bucket: 'flightcanvas',
        objectName: 'tiles/us_tiles/$tiles',
        pathToSave: filePath,
//! Fix here your paramns
        onReceiveProgress: (received, total) {
          if (total > 0) {
            // Fix progress calculation
//! Fix the calc (received / total) * 100
            final progress = received.toDouble() / total.toDouble() * 100;
            print('Download progress: ${(progress).toStringAsFixed(2)}%');
            //  print('Download progress: ${(progress * 100).toStringAsFixed(2)}%');
            _setDownloadProgress(
                progress); // Use _setDownloadProgress instead of _setProgress
            prefs.setInt('bytesTransferred_$tiles', received);
            notifyListeners(); // Ensure UI updates
          }
        },
      );
```

**Comment by jesussmile** [comment]
> Hi @jesussmile, sorry for putting a incorrect example on the package i will fix this.
> 
> But with the example that you gave, if you want the percent from the download correct you need to fix your code on the `onReceiveProgress: (total, received) {`, you changed the params, it shoud be `onReceiveProgress: (received, total) {` and fix the calc by doing `received / total * 100`
> 
> your code
> 
> ```dart
>   await CloudFlareR2.getObject(
>         bucket: 'flightcanvas',
>         objectName: 'tiles/us_tiles/$tiles',
>         pathToSave: filePath,
> //! Fix here your paramns
>         onReceiveProgress: (received, total) {
>           if (total > 0) {
>             // Fix progress calculation
> //! Fix the calc (received / total) * 100
>             final progress = received.toDouble() / total.toDouble() * 100;
>             print('Download progress: ${(progress).toStringAsFixed(2)}%');
>             //  print('Download progress: ${(progress * 100).toStringAsFixed(2)}%');
>             _setDownloadProgress(
>                 progress); // Use _setDownloadProgress instead of _setProgress
>             prefs.setInt('bytesTransferred_$tiles', received);
>             notifyListeners(); // Ensure UI updates
>           }
>         },
>       );
> ```

Yea i realized my mistake however there were still some cases showing negative values , you may want to take a look at the pull request.

**Comment by rodolfogoulart** [comment]
@jesussmile thanks man...

i meged the pull request and add example and bump the version on pub.dev

check there.

Closing this issue. If you have more to share you can re-open, or add another.

**Comment by jesussmile** [comment]
@rodolfogoulart  I just checked with ios, it works fine.

**Comment by rodolfogoulart** [comment]
Thanks man... 

I just add another call to, `listObjectsV2`

check the version **0.0.7**

**Comment by jesussmile** [comment]
Lol! Kinda funny as I did the same. Didn't send a pull request as I thought it wasn't necessary for this package!

**Comment by jesussmile** [comment]
Anyways this is my implementation 

```dart
import 'package:xml/xml.dart';


 static Future<List<Map<String, dynamic>>> listObjects({
    required String bucket,
    required String prefix,
    String region = 'us-east-1',
  }) async {
    assert(_signer != null,
        'Please call CloudFlareR2.init() before using this library');

    final urlRequest = AWSHttpRequest.get(
      Uri.https(_host, bucket, {
        'list-type': '2',
        'prefix': prefix,
      }),
      headers: {
        AWSHeaders.host: _host,
      },
    );

    final signedRequest = await _signer!.sign(
      urlRequest,
      credentialScope: _scope!,
      serviceConfiguration: _serviceConfiguration,
    );

    final response = await signedRequest.send().response;

    if (response.statusCode != 200) {
      throw Exception('Failed to list objects: ${response.statusCode}');
    }

    // Get response body as string
    final bodyBytes = await response.bodyBytes;
    final xmlString = String.fromCharCodes(bodyBytes);
    // print('XML Response: $xmlString');

    try {
      final document = XmlDocument.parse(xmlString);
      final objects = <Map<String, dynamic>>[];

      for (var node in document.findAllElements('Contents')) {
        final key = node.findElements('Key').firstOrNull?.text;
        final size = node.findElements('Size').firstOrNull?.text;

        if (key != null && size != null) {
          objects.add({
            'name': key,
            'size': int.parse(size),
          });
        }
      }

      return objects;
    } catch (e) {
      log('Error parsing XML: $e');
      rethrow;
    }
  }
```

**Comment by rodolfogoulart** [comment]
Cool man... I get to improve the other methods based on what you did, removing Dio

**Comment by jesussmile** [comment]
Have you tried implementing download cancellation or closing connections? I’m facing issues with canceling downloads—the previous download connection seems to persist.

**Comment by rodolfogoulart** [comment]
Hi @jesussmile 
No I didn't... If you have implement some similar with the new call I did, share with me, to implement 😆...
